name: Build Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup:
    name: Set Up Environment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run prebuild to generate Android and iOS folders
        run: npx expo prebuild

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Decode Keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/your-keystore-file.keystore

      - name: Set up Signing Configs
        run: |
          echo "RELEASE_STORE_FILE=$(pwd)/android/app/your-keystore-file.keystore" >> $GITHUB_ENV
          echo "RELEASE_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "RELEASE_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> $GITHUB_ENV

      - name: Build Android APK and AAB
        run: |
          cd android
          ./gradlew bundleRelease assembleRelease -Pandroid.injected.signing.store.file=$RELEASE_STORE_FILE -Pandroid.injected.signing.store.password=$RELEASE_STORE_PASSWORD -Pandroid.injected.signing.key.alias=$RELEASE_KEY_ALIAS -Pandroid.injected.signing.key.password=$RELEASE_KEY_PASSWORD
        env:
          JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.12-7/x64
          RELEASE_STORE_FILE: ${{ env.RELEASE_STORE_FILE }}
          RELEASE_STORE_PASSWORD: ${{ env.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ env.RELEASE_KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ env.RELEASE_KEY_PASSWORD }}

      - name: Upload APK and AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: |
            android/app/build/outputs/apk/release/app-release.apk
            android/app/build/outputs/bundle/release/app-release.aab
